---
name: Spotify Connect w/out Discovery
version: dev
slug: spotify
description: Play Spotify music on your Home Assistant device
url: https://github.com/Gadzhi13/addon-spotify-connect
arch:
  - aarch64
  - amd64
  - armv7
  - i386
host_network: false
audio: true
options:
  name: Zonglerassistant
  bitrate: 160
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  name: str
  bitrate: list(96|160|320)
  username: str?
  password: password?
